export const api = {
  category: '/api/category/create',
  products: '/api/product/create',
  register: '/api/user/register',
  login: '/api/user/login',
  favouriteList: '/api/favourite/list',
  favouriteAdd: '/api/favourite/add',
  favouriteDelete: '/api/favourite/delete',
  getProfile: '/api/user/profile',
  productDetail: '/api/product/detail',
  productByCategory: '/api/product/filter',
  getAllCategory: '/api/all',
  getSubCategory: '/api/subcategory/list',
  getCart: '/api/checkout/cart',
  addProduct: '/api/orders/add',
  changeProduct: '/api/orders/change',
  processBilling: '/api/payment/process/billing',
  processShipping: '/api/payment/process/shipping',
  processYourOrder: '/api/payment/process/your_order' , 
  successOrder: '/payment/success'  
};
